bazel server: reload on network changes, skip in CI
the server container starting before network changes
can trigger all sorts of weird errors like
```
java.io.IOException: Error downloading [https://github.com/google/go-containerregistry/releases/download/v0.18.0/go-containerregistry_Linux_x86_64.tar.gz] to /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/oci_crane_linux_amd64/temp750214973604621885/go-containerregistry_Linux_x86_64.tar.gz: Unknown host: github.com
```
this could be a nice quality of life improvement for a local dev environment

this is a second attempt since the first one was hostile to CI,
where the networking could change mid run quite a bit.

Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>