openapi: add missing MIME to subresources API definition
Without them, Kubernetes v2 -> v3 converter drops request body content
and ZAP scanner is complaining about it and aborts scanning:

    error: attribute paths.'/apis/subresources.kubevirt.io/v1/namespaces/{namespace}/virtualmachineinstances/{name}/addvolume'(put).requestBody.content
    is missing

Signed-off-by: Denis Ollier <dollierp@redhat.com>