Update libvirt: 9.0.0 -> 9.5.0
This patch updates to libvirt-9.5.0 [0]. Without this update we can't
run `make rpm-deps`.

By updating edk2 in the previous commit, bazel rpmtree finds a
the following conflict:

 > libvirt-daemon-driver-qemu-0:9.0.0-3.el9 conflicts with edk2-aarch64-0:20230524-2.el9

It can't find a solution, so it proceeds with:

 > Selecting libvirt-daemon-driver-qemu: libvirt-daemon-driver-qemu-0:9.0.0-3.el9
 > Selecting edk2-aarch64: edk2-aarch64-0:20230524-2.el9

Which leads to the failure:

 > Error: no solution found
 > Usage:
 >   bazeldnf rpmtree [flags]

[0] https://gitlab.com/redhat/centos-stream/rpms/libvirt/-/merge_requests/67
Signed-off-by: Victor Toso <victortoso@redhat.com>