build: fix tar2files error due to missing files
tar2files fails due to not being able find certain dependencies

```
Error: could not convert rpm at bazel-out/k8-fastbuild/bin/rpm/libvirt-devel_x86_64.tar: some files could not be found: map[/usr/lib64/libgcc_s-11-20240719.so.1:bazel-out/k8-fastbuild/bin/rpm/libvirt-libs_x86_64/usr/lib64/libgcc_s-11-20240719.so.1 /usr/lib64/libgcc_s.so.1:bazel-out/k8-fastbuild/bin/rpm/libvirt-libs_x86_64/usr/lib64/libgcc_s.so.1 /usr/lib64/libtirpc.so.3:bazel-out/k8-fastbuild/bin/rpm/libvirt-libs_x86_64/usr/lib64/libtirpc.so.3 /usr/lib64/libtirpc.so.3.0.0:bazel-out/k8-fastbuild/bin/rpm/libvirt-libs_x86_64/usr/lib64/libtirpc.so.3.0.0]
```

Checking the rpm in question - the files are no longer included in the
libvirt-libs rpm

```
bcarey@bcarey:~/Downloads$ rpm -qlp libvirt-libs-10.10.0-13.el9.x86_64.rpm  | grep libgcc
warning: libvirt-libs-10.10.0-13.el9.x86_64.rpm: Header OpenPGP V4 RSA/SHA256 signature, key ID 05b555b38483c65d: NOKEY
bcarey@bcarey:~/Downloads$
bcarey@bcarey:~/Downloads$ rpm -qlp libvirt-libs-10.10.0-13.el9.x86_64.rpm  | grep libtirpc
warning: libvirt-libs-10.10.0-13.el9.x86_64.rpm: Header OpenPGP V4 RSA/SHA256 signature, key ID 05b555b38483c65d: NOKEY
bcarey@bcarey:~/Downloads$
```

Remove these from rpm/BUILD.bazel

Signed-off-by: Brian Carey <bcarey@redhat.com>