Update edk2: 20230301 -> 20230524
Updating to the latest version of edk2 [0].
Without this update, make rpm-deps fails with:

    Error: Package edk2-ovmf-0:20230301gitf80f052277c8-2.el9 does not exist

[0] https://gitlab.com/redhat/centos-stream/rpms/edk2/-/merge_requests/41
Signed-off-by: Victor Toso <victortoso@redhat.com>